### Get all Pokemons in the database
GET http://localhost:4000/pokemon/



### Get one pokemon
GET http://localhost:4000/pokemon/1



### Create a new pokemon
POST http://localhost:4000/pokemon/
Content-Type: application/json

{
    "name": "nuemon",
    "type": "water",
    "hp": 79,
    "attack": 85,
    "defense": 60,
    "sp_attack": 55,
    "sp_defense": 60,
    "speed": 71
}



### Delete a pokemon
DELETE http://localhost:4000/pokemon/1



### Update a pokemon by pokemonid
PUT http://localhost:4000/pokemon/2
Content-Type: application/json

{   
    "name": "marisamon",
    "type": "water",
	"hp": 40,
	"attack": 30,
	"defense": 50,
	"sp_attack": 55,
	"sp_defense": 55,
	"speed": 1000
}